# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zach Warner
tagline:          'political scientist'
url:              http://zachwarner.net
baseurl:          /

author:
  name:           'Zach Warner'
  url:            https://twitter.com/ZachMWarner