# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zach Warner
tagline:          'Political scientist'
description:      'Postdoctoral research fellow, Centre for Political and Legal Analytics, Cardiff University'
url:              http://zachwarner.net
baseurl:          /

author:
  name:           'Zach Warner'
  url:            https://twitter.com/ZachMWarner